spring:
  application:
    name: eureka-server #服务名称
server:  
  port: ${CONTAINER_PORT:18001} #服务端口
  security:
    basic:
      enabled: false #注册安全认证开关
    user:
      name: all
      password: 123456
eureka:
  instance:
    # hostname: ${DOMAIN_NAME:192.168.0.6} #服务主机名称
    prefer-ip-address: true
  client:
    # 集群的情况下设置为true
    registerWithEureka: ${BOOL_REGISTER:false}
    # 集群的情况下设置为true
    fetchRegistry:  ${BOOL_FETCH:false}
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_ADDRESS:http://all:123456@127.0.0.1:18001/eureka/}
